apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
    app: {{ .Release.Name }}-backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-frontend
