import { ExecutiveDashboardSummary, ATCDataPoint } from '../types/dashboard';
import { GridAlert } from '../types/alert';
import { SmartMeterTelemetry, ShapExplanationResponse } from '../types/telemetry';
import { GridTopologyResponse } from '../types/topology';

export const MOCK_DASHBOARD_SUMMARY: ExecutiveDashboardSummary = {
  active_smart_meters: {
    id: 'kpi-1',
    title: 'Active Smart Meters',
    value: '148,920',
    unit: 'meters',
    change_percentage: 2.4,
    trend: 'UP',
    status: 'NOMINAL',
    last_updated: new Date().toISOString(),
    description: 'Online reporting meters across 3 subregions',
  },
  active_feeders: {
    id: 'kpi-2',
    title: 'Active Feeders / Substations',
    value: '14 / 3',
    unit: 'units',
    change_percentage: 0,
    trend: 'STABLE',
    status: 'NOMINAL',
    last_updated: new Date().toISOString(),
    description: 'Distribution network nodes operational',
  },
  transformer_health_index: {
    id: 'kpi-3',
    title: 'Transformer Health Index',
    value: '94.2%',
    unit: '%',
    change_percentage: -1.2,
    trend: 'DOWN',
    status: 'WARNING',
    last_updated: new Date().toISOString(),
    description: 'Thermal & load balance index',
  },
  today_energy_loss_mwh: {
    id: 'kpi-4',
    title: "Today's Energy Loss",
    value: '42.8',
    unit: 'MWh',
    change_percentage: 8.5,
    trend: 'UP',
    status: 'WARNING',
    last_updated: new Date().toISOString(),
    description: 'Unmetered AT&C energy discrepancy',
  },
  financial_loss_at_risk: {
    id: 'kpi-5',
    title: 'Financial Loss at Risk',
    value: '₹3,42,500',
    unit: 'INR',
    change_percentage: 12.1,
    trend: 'UP',
    status: 'CRITICAL',
    last_updated: new Date().toISOString(),
    description: 'Estimated unbilled revenue loss today',
  },
  detected_theft_nodes: {
    id: 'kpi-6',
    title: 'Detected Anomaly Nodes',
    value: '18',
    unit: 'nodes',
    change_percentage: 5.8,
    trend: 'UP',
    status: 'CRITICAL',
    last_updated: new Date().toISOString(),
    description: 'High-probability theft anomaly meters',
  },
  ai_confidence_score: {
    id: 'kpi-7',
    title: 'AI Model Accuracy',
    value: '96.4%',
    unit: '%',
    change_percentage: 0.8,
    trend: 'UP',
    status: 'NOMINAL',
    last_updated: new Date().toISOString(),
    description: 'Ensemble model cross-validation score',
  },
  revenue_recovered_ytd: {
    id: 'kpi-8',
    title: 'Revenue Recovered YTD',
    value: '₹1.24 Cr',
    unit: 'INR',
    change_percentage: 18.3,
    trend: 'UP',
    status: 'NOMINAL',
    last_updated: new Date().toISOString(),
    description: 'Verified audits & penal recoveries',
  },
};

export const MOCK_ALERTS: GridAlert[] = [
  {
    alert_id: 'alt-101',
    meter_id: 'MTR-44822',
    consumer_name: 'Apex Industrial Complex',
    transformer_id: 'TR-102',
    feeder_id: 'FDR-04',
    substation_id: 'SUB-01',
    severity: 'CRITICAL',
    anomaly_type: 'PARTIAL_BYPASS',
    risk_score: 0.94,
    financial_loss_estimate: 84500,
    message: 'Sudden 78% drop in active draw during peak hours without load shift.',
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    is_acknowledged: false,
  },
  {
    alert_id: 'alt-102',
    meter_id: 'MTR-88190',
    consumer_name: 'Metro Cold Storage',
    transformer_id: 'TR-105',
    feeder_id: 'FDR-02',
    substation_id: 'SUB-01',
    severity: 'HIGH',
    anomaly_type: 'METER_FREEZE',
    risk_score: 0.88,
    financial_loss_estimate: 62000,
    message: 'Flatline consumption telemetry detected despite temperature fluctuation.',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    is_acknowledged: false,
  },
  {
    alert_id: 'alt-103',
    meter_id: 'MTR-31044',
    consumer_name: 'GreenValley Feeder Line',
    transformer_id: 'TR-201',
    feeder_id: 'FDR-07',
    substation_id: 'SUB-02',
    severity: 'HIGH',
    anomaly_type: 'PHASE_IMBALANCE',
    risk_score: 0.76,
    financial_loss_estimate: 41200,
    message: 'Phase B current neutral imbalance exceeds 35% thermal tolerance.',
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    is_acknowledged: false,
  },
  {
    alert_id: 'alt-104',
    meter_id: 'MTR-99012',
    consumer_name: 'Shree Krishna Mills',
    transformer_id: 'TR-304',
    feeder_id: 'FDR-11',
    substation_id: 'SUB-03',
    severity: 'MEDIUM',
    anomaly_type: 'DIRECT_HOOKING',
    risk_score: 0.62,
    financial_loss_estimate: 28000,
    message: 'Unmetered transformer delta output discrepancy (14.2 kWh/h unaccounted).',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    is_acknowledged: true,
  },
];

export const MOCK_ATC_TREND: ATCDataPoint[] = [
  { timestamp: '00:00', expected_draw_kwh: 420, actual_draw_kwh: 415, loss_percentage: 1.2, unaccounted_kwh: 5 },
  { timestamp: '03:00', expected_draw_kwh: 380, actual_draw_kwh: 375, loss_percentage: 1.3, unaccounted_kwh: 5 },
  { timestamp: '06:00', expected_draw_kwh: 510, actual_draw_kwh: 485, loss_percentage: 4.9, unaccounted_kwh: 25 },
  { timestamp: '09:00', expected_draw_kwh: 780, actual_draw_kwh: 710, loss_percentage: 8.9, unaccounted_kwh: 70 },
  { timestamp: '12:00', expected_draw_kwh: 890, actual_draw_kwh: 790, loss_percentage: 11.2, unaccounted_kwh: 100 },
  { timestamp: '15:00', expected_draw_kwh: 920, actual_draw_kwh: 810, loss_percentage: 11.9, unaccounted_kwh: 110 },
  { timestamp: '18:00', expected_draw_kwh: 980, actual_draw_kwh: 820, loss_percentage: 16.3, unaccounted_kwh: 160 },
  { timestamp: '21:00', expected_draw_kwh: 850, actual_draw_kwh: 730, loss_percentage: 14.1, unaccounted_kwh: 120 },
];

export const MOCK_TELEMETRY: SmartMeterTelemetry = {
  meter_id: 'MTR-44822',
  consumer_name: 'Apex Industrial Complex',
  substation_id: 'SUB-01',
  feeder_id: 'FDR-04',
  transformer_id: 'TR-102',
  latitude: 28.6139,
  longitude: 77.209,
  timestamp: new Date().toISOString(),
  active_power_kwh: 1.2,
  expected_power_kwh: 5.4,
  voltage_v: 231.5,
  current_a: 5.2,
  power_factor: 0.72,
  temperature_c: 44.2,
  risk_score: 0.94,
  anomaly_type: 'PARTIAL_BYPASS',
};

export const MOCK_SHAP_EXPLANATION: ShapExplanationResponse = {
  meter_id: 'MTR-44822',
  overall_risk_score: 0.94,
  ai_summary:
    'High theft probability (94%) detected due to 78% drop in peak-hour active consumption with low power factor and active transformer phase mismatch.',
  contributions: [
    {
      feature_name: 'Peak Hour Consumption Drop',
      feature_value: '1.2 kWh vs 5.4 kWh Exp',
      shap_score: 0.42,
      description: 'Active draw dropped significantly during high industrial operational hours.',
    },
    {
      feature_name: 'Transformer Load Imbalance',
      feature_value: '32.4% Delta',
      shap_score: 0.28,
      description: 'Upstream transformer energy output exceeds total downstream meter sum.',
    },
    {
      feature_name: 'Power Factor Degradation',
      feature_value: '0.72 PF',
      shap_score: 0.14,
      description: 'Degraded power factor indicative of shunt bypass resistor installation.',
    },
    {
      feature_name: 'Historical Normal Pattern',
      feature_value: '90 Days High Draw',
      shap_score: -0.08,
      description: 'Historical consumer reliability slightly mitigates instant risk baseline.',
    },
  ],
};

export const MOCK_TOPOLOGY_DATA: GridTopologyResponse = {
  nodes: [
    {
      id: 'sub-1',
      type: 'substation',
      label: 'Substation Alpha (33kV)',
      status: 'nominal',
      risk_score: 0.05,
      loss_percentage: 1.2,
      position: { x: 250, y: 50 },
      details: { capacity_kva: 50000, connected_consumers: 148920, current_load_kw: 32400 },
    },
    {
      id: 'fdr-4',
      type: 'feeder',
      label: 'Feeder FDR-04 (11kV)',
      status: 'warning',
      risk_score: 0.68,
      loss_percentage: 14.2,
      position: { x: 100, y: 200 },
      details: { capacity_kva: 10000, connected_consumers: 12400, current_load_kw: 7800 },
    },
    {
      id: 'fdr-2',
      type: 'feeder',
      label: 'Feeder FDR-02 (11kV)',
      status: 'nominal',
      risk_score: 0.12,
      loss_percentage: 2.1,
      position: { x: 400, y: 200 },
      details: { capacity_kva: 10000, connected_consumers: 11000, current_load_kw: 6200 },
    },
    {
      id: 'tr-102',
      type: 'transformer',
      label: 'Transformer TR-102',
      status: 'critical',
      risk_score: 0.94,
      loss_percentage: 32.8,
      position: { x: 50, y: 350 },
      details: { capacity_kva: 500, connected_consumers: 48, current_load_kw: 310 },
    },
    {
      id: 'mtr-44822',
      type: 'meter',
      label: 'Smart Meter #44822',
      status: 'critical',
      risk_score: 0.94,
      loss_percentage: 78.0,
      position: { x: 50, y: 500 },
      details: { connected_consumers: 1, current_load_kw: 1.2 },
    },
  ],
  edges: [
    { id: 'e1', source: 'sub-1', target: 'fdr-4', status: 'high_loss', load_flow_rate: 2 },
    { id: 'e2', source: 'sub-1', target: 'fdr-2', status: 'nominal', load_flow_rate: 1 },
    { id: 'e3', source: 'fdr-4', target: 'tr-102', status: 'high_loss', load_flow_rate: 3 },
    { id: 'e4', source: 'tr-102', target: 'mtr-44822', status: 'high_loss', load_flow_rate: 4 },
  ],
};
