"""initial_schema

Revision ID: 071f166ebae9
Revises: 
Create Date: 2026-07-30 18:02:44.458262

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '071f166ebae9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('capacity_mva', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_substations_code'), 'substations', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'ENGINEER', 'INSPECTOR', 'VIEWER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('target_entity', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('substation_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('nominal_voltage_kv', sa.Float(), nullable=False),
    sa.Column('current_load_kw', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeders_code'), 'feeders', ['code'], unique=True)
    op.create_table('transformers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('feeder_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('capacity_kva', sa.Float(), nullable=False),
    sa.Column('phase_count', sa.Integer(), nullable=False),
    sa.Column('health_index', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformers_code'), 'transformers', ['code'], unique=True)
    op.create_table('smart_meters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transformer_id', sa.String(), nullable=False),
    sa.Column('meter_number', sa.String(), nullable=False),
    sa.Column('consumer_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_meters_meter_number'), 'smart_meters', ['meter_number'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.Column('transformer_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('financial_loss_estimate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['smart_meters.id'], ),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.Column('assigned_inspector_id', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'AUDITED', name='inspectionstatus'), nullable=False),
    sa.Column('financial_loss_estimate', sa.Float(), nullable=False),
    sa.Column('audit_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['smart_meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_readings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meter_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_power_kwh', sa.Float(), nullable=False),
    sa.Column('expected_power_kwh', sa.Float(), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.Column('current_a', sa.Float(), nullable=False),
    sa.Column('power_factor', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('anomaly_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meter_id'], ['smart_meters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_readings_timestamp'), 'telemetry_readings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_readings_timestamp'), table_name='telemetry_readings')
    op.drop_table('telemetry_readings')
    op.drop_table('inspections')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_smart_meters_meter_number'), table_name='smart_meters')
    op.drop_table('smart_meters')
    op.drop_index(op.f('ix_transformers_code'), table_name='transformers')
    op.drop_table('transformers')
    op.drop_index(op.f('ix_feeders_code'), table_name='feeders')
    op.drop_table('feeders')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_substations_code'), table_name='substations')
    op.drop_table('substations')
    # ### end Alembic commands ###
